### ISSUE TITLE
Ajouter la récupération de mot de passe

### ISSUE THREAD

**Issue by MrGecko** [chartes/adele-vue#13]
La fonctionnalité de récupération de mot de passe doit être implémentée et accessible via la page de login comme on le fait habituellement ("mot de passe oublié ?").
Un mot de passe temporaire doit être envoyé par mail (solution la plus simple).

Objectifs :
- Proposer le lien "mot de passe oublié ?" sur la page de login
- Envoyer par mail un nouveau mot de passe à l'utilisateur

**Comment by MrGecko** [comment]
Voir si #12 impacte cette issue.

**Comment by fbessou** [comment]
Une solution alternative serait d'envoyer un mail contenant un token pour récupérer le mot de passe:
- ajouter une table | user_id | token | date expiration |
- ajouter api  POST`/api/reset-password` qui prend un token de récupération et un mot de passe et modifie le mot de passe si la date expiration n'est pas passée. 
- créer une page de récupération GET `/reset-password?token=<token>` avec un formulaire [Nouveau mot de passe] [Confirmer mot de passe]. La soumission du formulaire déclenche l'appel à l'api `/api/reset-password`
- ajouter bouton "Mot de passe oublié" sur `/login` qui crée un token, envoie un email avec un lien de la forme `/reset-password?token=1234567890abcdef` et affiche un message "Un email de récupération vient de vous être envoyé." (même si l'utilisateur n'existe pas).

**Comment by fbessou** [comment]
L'API doit envoyer un mail contenant un lien de récupération à l'utilisateur. Le lien doit pointer vers une URL du client (https://dev.chartes.psl.eu/adele/reset-password?token=<token> par exemple ou http://localhost:9090/adele/reset-password?token=<token> en local) mais je n'ai pas l'impression que l'API soit au courant de l'URL du client. Est-ce que je passe à côté de quelque chose ?

Sinon la seule solution sécurisée que je vois serait de toujours envoyer l'url de l'API auquel on retire le suffixe `/api/1.0/` : `config["SERVER_URL"]+/reset-password?token=<token>`. 

@MrGecko  As-tu un avis sur la question ?

**Comment by MrGecko** [comment]
Je crois qu'il existe déjà ```config["APP_URL_PREFIX"]``` pour ces cas là
Il existe un raccourci dans ```app/__init__.py```: 
```python
    def with_url_prefix(url):
        from flask import request
        from flask import current_app
        return "".join((request.host_url[:-1], current_app.config["APP_URL_PREFIX"], url))
```

**Comment by MrGecko** [comment]
Je crois qu'il existe déjà ```config["APP_URL_PREFIX"]``` pour ces cas là
Il existe un raccourci dans ```app/__init__.py```: 
```python
    def with_url_prefix(url):
        from flask import request
        from flask import current_app
        return "".join((request.host_url[:-1], current_app.config["APP_URL_PREFIX"], url))
```

**Comment by fbessou** [comment]
Effectivement, j'étais passé à côté. Une PR devrait bientôt arriver :)
L'implémentation de la récupération de mot de passe est légèrement différente de ce que je décrivais plus tôt:
plutôt que de stocker un token en base, j'envoie une URL contenant un JWT qui expire au bout de 20 minutes. Ça a le mérite de ré-utiliser jwt et d'éviter les migrations.
