### ISSUE TITLE
[Analyse] Bugs d'affichage Mirador

### ISSUE THREAD

**Issue by MrGecko** [chartes/adele-vue#14]
L'intégration de Mirador dans nos projets Vuejs pose quelques soucis, semblerait-il de css.

**Bug 1 :**
Bien souvent au chargement d'une page, l'UI de navigation de la visionneuse n'est pas affiché correctement :
![image](https://user-images.githubusercontent.com/65418/144028163-1cc19bc5-9eaf-45e9-ad66-9b8da4a90b7e.png)
Dans ces cas là, il faut recharger la page pour le bug disparaisse.

**Bug 2 :**
L'image n'apparaît pas d'elle-même et il faut cliquer et se déplacer pour que l'affichage soit correct.
![image](https://user-images.githubusercontent.com/65418/144028791-eb164b80-dbab-47cf-8f44-bc9b52dfe266.png)
_Le manifest est bien chargé mais si on ne clique pas on ne voit rien_

**Objectifs :** 
- Déterminer l'origine de ces deux bugs 
- Proposer si possible une solution, sans l'implémenter

**Comment by fbessou** [comment]
J'ai envoyé une PR avec mon interprétation du premier problème, je me suis permis d'écrire le bout de code correspondant, étant donné que le diff est minime.

**Comment by MrGecko** [comment]
@fbessou après une période de tests sur nos différents environnements, le problème apparaît (hélas) toujours à l'identique.

**Comment by fbessou** [comment]
Je viens de réussir à reproduire en local en compilant en mode production. Le problème arrive si je passe par un `npm run build` ou par un `npm run serve -- --mode=production`.
